// Generated by gencpp from file webots_ros/DarwinOP2State.msg
// DO NOT EDIT!


#ifndef WEBOTS_ROS_MESSAGE_DARWINOP2STATE_H
#define WEBOTS_ROS_MESSAGE_DARWINOP2STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace webots_ros
{
template <class ContainerAllocator>
struct DarwinOP2State_
{
  typedef DarwinOP2State_<ContainerAllocator> Type;

  DarwinOP2State_()
    : header()
    , position()
    , torque()
    , l_fsr_readings()
    , r_fsr_readings()  {
    }
  DarwinOP2State_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , torque(_alloc)
    , l_fsr_readings(_alloc)
    , r_fsr_readings(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _position_type;
  _position_type position;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _torque_type;
  _torque_type torque;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _l_fsr_readings_type;
  _l_fsr_readings_type l_fsr_readings;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _r_fsr_readings_type;
  _r_fsr_readings_type r_fsr_readings;





  typedef boost::shared_ptr< ::webots_ros::DarwinOP2State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webots_ros::DarwinOP2State_<ContainerAllocator> const> ConstPtr;

}; // struct DarwinOP2State_

typedef ::webots_ros::DarwinOP2State_<std::allocator<void> > DarwinOP2State;

typedef boost::shared_ptr< ::webots_ros::DarwinOP2State > DarwinOP2StatePtr;
typedef boost::shared_ptr< ::webots_ros::DarwinOP2State const> DarwinOP2StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webots_ros::DarwinOP2State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webots_ros::DarwinOP2State_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace webots_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'webots_ros': ['/home/hrvl/catkin_ws/src/webots_ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::webots_ros::DarwinOP2State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_ros::DarwinOP2State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webots_ros::DarwinOP2State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webots_ros::DarwinOP2State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_ros::DarwinOP2State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_ros::DarwinOP2State_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webots_ros::DarwinOP2State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "984c899e3714c52666000e07b8205c74";
  }

  static const char* value(const ::webots_ros::DarwinOP2State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x984c899e3714c526ULL;
  static const uint64_t static_value2 = 0x66000e07b8205c74ULL;
};

template<class ContainerAllocator>
struct DataType< ::webots_ros::DarwinOP2State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webots_ros/DarwinOP2State";
  }

  static const char* value(const ::webots_ros::DarwinOP2State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webots_ros::DarwinOP2State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64[] position \n\
float64[] torque\n\
float64[] l_fsr_readings\n\
float64[] r_fsr_readings\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::webots_ros::DarwinOP2State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webots_ros::DarwinOP2State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.torque);
      stream.next(m.l_fsr_readings);
      stream.next(m.r_fsr_readings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DarwinOP2State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webots_ros::DarwinOP2State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webots_ros::DarwinOP2State_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "torque[]" << std::endl;
    for (size_t i = 0; i < v.torque.size(); ++i)
    {
      s << indent << "  torque[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.torque[i]);
    }
    s << indent << "l_fsr_readings[]" << std::endl;
    for (size_t i = 0; i < v.l_fsr_readings.size(); ++i)
    {
      s << indent << "  l_fsr_readings[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.l_fsr_readings[i]);
    }
    s << indent << "r_fsr_readings[]" << std::endl;
    for (size_t i = 0; i < v.r_fsr_readings.size(); ++i)
    {
      s << indent << "  r_fsr_readings[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.r_fsr_readings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBOTS_ROS_MESSAGE_DARWINOP2STATE_H
